### ISSUE TITLE
Add a README.md

### ISSUE THREAD

**Issue by divyankkarolia97** [divyankkarolia97/bol_na_bhai#2]
app is running on **http://bolnabhai.herokuapp.com.** Study what it does and create a README.md.
**Be Creative, do it any way you wish.**

**Comment by Zeustopher** [comment]
I'll take an initial pass at it. Pull Request will come shortly.

Happy Hacktoberfest!

**Comment by divyankkarolia97** [comment]
@Zeustopher Go ahead :+1:
